from design.games import games

conditions={
	"tangled":{
		"name":"Tangled",
		"skin":"condition_bad",
		"ui":False,
		"debuff":True,
		"set_speed":24,
		"duration":12000,
	},
	"sugarrush":{
		"skin":"candycanesword",
		"name":"Sugar Rush",
		"frequency":240,
		"duration":10*1000,
		"mp_cost":-200,
		"buff":True,
		"ui":True,
	},
	"power":{
		"skin":"powerglove",
		"name":"Power",
		"frequency":360,
		"duration":4*1000,
		"mp_cost":-200,
		"buff":True,
		"ui":True,
	},
	"weakness":{
		"skin":"condition_bad",
		"name":"Weakness",
		"debuff":True,
		"ui":True,
		"speed":-30,
		"dex":-10,
		"str":-10,
		"duration":20000,
	},
	"xpower":{
		"skin":"goldenpowerglove",
		"name":"Power",
		"frequency":480,
		"duration":6*1000,
		"mp_cost":-300,
		"buff":True,
		"ui":True,
	},
	"stack":{
		"skin":"skill_stack",
		"name":"Pure Damage",
		"explanation":"Bonus damage for each rogue attack",
		"debuff":True,
	},
	"woven":{
		"skin":"spidersilk",
		"name":"Woven",
		"explanation":"Slowed down from all the spider silk sticking around.",
		"ui":True,
		"debuff":True,
		"speed":-10,
		"duration":1000,
	},
	"energized":{
		"skin":"skill_energize",
		"name":"Energized",
		"buff":True,
		"frequency":80,
		"duration":800,
		"buff":True,
		"ui":True,
	},
	"mcourage":{
		"skin":"skill_mcourage",
		"name":"Merchant's Courage",
		"speed":25,
		"evasion":40,
		"courage":5,
		"mcourage":5,
		"pcourage":5,
		"duration":10000,
		"ui":True,
		"buff":True,
	},
	"mfrenzy":{
		"skin":"skill_mfrenzy",
		"name":"Merchant's Frenzy",
		"frequency":800,
		"duration":5000,
		"mp_cost":-20,
		"output":40,
		"ui":True,
		"buff":True,
	},
	"mshield":{
		"skin":"skill_mshield",
		"name":"Mana Shield",
		"ui":True,
		"buff":True,
	},
	"phasedout":{
		"skin":"skill_phaseout",
		"name":"Phased Out",
		"frequency":-40,
		"speed":-16,
		"evasion":64,
		"duration":5000,
		"ui":True,
		"buff":True,
	},
	"hardshell":{
		"skin":"skill_hardshell",
		"name":"Hard Shell",
		"armor":800,
		"set_speed":10,
		"duration":8000,
		"buff":True,
	},
	"reflection":{
		"skin":"buff_reflection",
		"name":"Reflective Shield",
		"reflection":20,
		"cap_reflection":50,
		"duration":5000,
		"ui":True,
		"buff":True,
	},
	"eburn":{
		"skin":"essenceoffire",
		"name":"Burn",
		"intensity":"burnd",
		"interval":200,
		"damage":50,
		"duration":12*1000,
		"speed":5,
		"ui":True,
		"debuff":True,
	},
	"newcomersblessing":{
		"skin":"newcomersblessing",
		"name":"Newcomers' Blessing",
		"duration":30*60*1000,
		"luck":10,
		"gold":10,
		"xp":10,
		"aura":True,
		"ui":True,
		"persistent":True,
	},
	"eheal":{
		"skin":"essenceoflife",
		"name":"Rejuvenate",
		"interval":320,
		"heal":200,
		"duration":4*1000,
		"ui":True,
		"buff":True,
	},
	"rspeed":{
		"skin":"buff_speed",
		"name":"Rogue Swiftness",
		"speed":7,
		"frequency":8,
		"duration":45*60*1000,
		"buff":True,
		"ui":True,
	},
	"massproduction":{
		"skin":"skill_massproduction",
		"name":"Mass Production",
		"explanation":"Speeds up the next upgrade or compound 50%",
		"duration":10*1000,
		"buff":True,
		"ui":True,
	},
	"massproductionpp":{
		"skin":"skill_massproductionpp",
		"name":"Mass Production++",
		"explanation":"Speeds up the next upgrade or compound 90%",
		"duration":10*1000,
		"buff":True,
		"ui":True,
	},
	"darkblessing":{
		"skin":"skill_dbuff",
		"name":"Dark Blessing",
		"output":25,
		"duration":8*1000,
		"buff":True,
		"ui":True,
	},
	"warcry":{
		"skin":"skill_warcry",
		"name":"War Cry",
		"frequency":10,
		"speed":20,
		"armor":160,
		"resistance":160,
		"duration":8*1000,
		"buff":True,
		"ui":True,
	},
	"purifier":{
		"skin":"skill_purify",
		"name":"Purifier",
		"frequency":20,
		"output":20,
		"str":30,
		"duration":8*1000,
		"buff":True,
		"ui":True,
	},
	"mluck":{
		"skin":"buff_luck",
		"name":"Good Luck",
		"luck":12,
		"duration":60*60*1000,
		"buff":True,
		"ui":True,
		"persistent":True,
	},
	"withdrawal":{
		"skin":"withdrawal",
		"name":"Withdrawal",
		"speed":-20,
		"frequency":-30,
		"dex":-20,
		"str":-5,
		"mp":-300,
		"duration":180*60*1000,
		"ui":True,
		"debuff":True,
		"persistent":True,
	},
	"penalty_cd":{
		"skin":"condition_bad",
		"name":"Penalty Cooldown",
		"explanation":"The remaining duration of this condition is added any skill you use. Teleporting adds 3s, magiporting adds around 800ms, some item operations add 100-200ms.",
		"debuff":True,
	},
	"xshotted":{
		"skin":"xshotted",
		"name":"X-Shot",
		"explanation":"Good luck trying to find a tavern to play in.",
		"duration":12*60*60*1000,
		"debuff":True,
		"ui":True,
		"persistent":True,
	},
	"notverified":{
		"skin":"notverified",
		"name":"Not Verified",
		"explanation":"Reduced luck and gold until the associated email address is verified.",
		"luck":-25,
		"gold":-25,
		"debuff":True,
		"technical":True,
		"ui":True,
		"persistent":True,
	},
	"authfail":{
		"skin":"notverified",
		"name":"Authorization Failure",
		"explanation":"Your account has failed an internal authorization routine. This might've happened if you haven't logged on from Steam or Mac App Store since this new system was implemented. So just opening the non-web game client once, starting one character, hanging 1-2 minutes on a server and logging out will be enough to correct this mistake. If it persists unexpectedly email hello@adventure.land",
		"luck":-85,
		"gold":-85,
		"xp":-20,
		"debuff":True,
		"technical":True,
		"ui":True,
		"persistent":True,
	},
	"hopsickness":{
		"skin":"condition_bad",
		"name":"Hop Sickness",
		"explanation":"You are not in your home server! Go see Bean in Mainland square for a change.",
		"luck":-80,
		"gold":-80,
		"xp":-80,
		"output":-20,
		"ui":True,
		"debuff":True,
		"persistent":True,
		"duration":1000*60*12,
		"special":"snakeoil",
	},
	"fullguard":{
		"skin":"fullguard",
		"name":"Full Guard",
		"ui":True,
		"resistance":10000,
		"armor":10000,
		"buff":True,
		"persistent":True,
	},
	"fullguardx":{
		"skin":"fullguard",
		"name":"Full Guard",
		"ui":True,
		"avoidance":99,
		"buff":True,
		"persistent":True,
	},
	"stunned":{
		"name":"Stunned",
		"skin":"condition_bad",
		"ui":True,
		"blocked":True,
		"debuff":True,
		"duration":3200,
	},
	"deepfreezed":{
		"name":"Deepfreezed",
		"skin":"condition_bad",
		"duration":12000,
		"ui":True,
		"blocked":True,
		"debuff":True,
	},
	"invincible":{
		"name":"Invincible",
		"skin":"condition_positive",
		"explanation":"When you spawn in a PVP area. This prevents you from receiving damage or marked as engaged in PVP. If you get attacked, disconnect before this runs out - or fight!",
		"duration":6000,
		"persistent":True,
	},
	"frozen":{
		"name":"Frozen",
		"skin":"frostbow",
		"ui":True,
		"debuff":True,
		"duration":5000,
	},
	"burned":{
		"name":"Burned",
		"skin":"fireblade",
		"interval":210,
		"ui":True,
		"debuff":True,
	},
	"shocked":{
		"name":"Shocked",
		"skin":"essenceofthunder",
		"explanation":"Imminent magical damage",
		"duration":1600,
		"ui":True,
		"debuff":True,
	},
	"fingered":{
		"name":"Deep Meditation",
		"skin":"condition_neutral",
		"resistance":1600,
		"evasion":96,
		"blocked":True,
		"debuff":True,
	},
	"stoned":{
		"name":"Stoned",
		"skin":"condition_neutral",
		"duration":4000,
		"blocked":True,
		"debuff":True,
	},
	"easterluck":{
		"skin":"easterluck",
		"name":"Easter Luck",
		"luck":100,
		"duration":24*60*60*1000,
		"buff":True,
		"ui":True,
		"persistent":True,
	},
	"sanguine":{
		"skin":"sanguine",
		"lifesteal":1,
		"name":"Vampiric Aura",
		"attr0":"lifesteal",
		"buff":True,
		"ui":True,
		"aura":True,
		"duration":30*1000,
	},
	"mlifesteal":{
		"skin":"lifestealscroll",
		"name":"Lifesteal",
		"lifesteal":2.5,
		"duration":60*60*1000,
		"buff":True,
		"ui":True,
	},
	"holidayspirit":{
		"skin":"holidayspirit",
		#"name":"Xmas Spirit",
		"name":"Holiday Spirit",
		"luck":20,
		"gold":20,
		"xp":20,
		"duration":24*60*60*1000,
		"buff":True,
		"ui":True,
		"persistent":True,
	},
	"halloween0":{
		"skin":"halloween0",
		"name":"Halloween Spirit",
		"luck":5,
		"gold":5,
		"xp":100,
		"duration":48*60*60*1000,
		"buff":True,
		"ui":True,
		"persistent":True,
	},
	"halloween1":{
		"skin":"halloween1",
		"name":"Halloween Spirit",
		"luck":5,
		"gold":5,
		"xp":50,
		"output":2,
		"duration":24*60*60*1000,
		"buff":True,
		"ui":True,
		"persistent":True,
	},
	"halloween2":{
		"skin":"halloween2",
		"name":"Halloween Spirit",
		"output":3,
		"luck":5,
		"gold":5,
		"xp":10,
		"duration":8*60*60*1000,
		"buff":True,
		"ui":True,
		"persistent":True,
	},
	# "xmas":{
	# 	"skin":"xmas",
	# 	#"name":"Xmas Spirit",
	# 	"name":"Blessing of 2018",
	# 	"luck":200,
	# 	"gold":200,
	# 	"xp":200,
	# 	"duration":24*60*60*1000,
	# 	"buff":True,
	# 	"ui":True,
	# },
	# "xmas2":{
	# 	"skin":"xmas",
	# 	#"name":"Xmas Spirit",
	# 	"name":"Blessing of 2019",
	# 	"luck":50,
	# 	"gold":50,
	# 	"xp":50,
	# 	"evasion":10,
	# 	#"ability":"secondchance",
	# 	#"attr0":20,
	# 	"duration":48*60*60*1000,
	# 	"buff":True,
	# 	"ui":True,
	# 	"note":"Technically our third new year, second year of our tree and the buff :)"
	# },
	"slowness":{
		"skin":"slowness",
		"name":"Slowness",
		"skin":"condition_neutral",
		"explanation":"Things like spiderwebs cause you to slow down.",
		"speed":-40,
		"ui":True,
		"debuff":True,
	},
	"poisoned":{
		"name":"Poison",
		"skin":"poison",
		"duration":5000,
		"frequencym":0.8,
		"potionsm":0.5,
		"healm":0.25,
		"debuff":True,
	},
	"cursed":{
		"name":"Cursed",
		"skin":"condition_bad",
		"output":-20,
		"incdmgamp":20,
		"speed":-20,
		"duration":5000,
		"debuff":True,
	},
	"dampened":{
		"name":"Dampened",
		"skin":"dampened",
		"explanation":"Can't blink or teleport",
		"duration":300,
		"debuff":True,
	},
	"poisonous":{
		"skin":"skill_pcoat",
		"name":"Poisonous",
		"ui":True,
		"buff":True,
		"duration":5000,
	},
	"invis":{
		"skin":"skill_invis",
		"name":"Invisible",
		"explanation":"Hidden from everyone else until you attack",
		"buff":True,
	},
	"licenced":{
		"skin":"licence",
		"name":"Licenced to Kill",
		"explanation":"A special, temporary immunity",
		"ui":True,
		"buff":True,
	},
	"charmed":{
		"skin":"charmer",
		"name":"Charmed",
		"explanation":"Mellow like a warm kitty",
		"ui":True,
		"duration":30000,
		"debuff":True,
	},
	"monsterhunt":{
		"skin":"quest_monsterhunt",
		"name":"On The Hunt",
		"ui":True,
		"duration":1800000,
		"persistent":True,
	},
	"marked":{
		"skin":"skill_huntersmark",
		"name":"Marked",
		"explanation":"Marked by a ranger for death. Receive 10% more damage and can't stealth.",
		"ui":True,
		"incdmgamp":10,
		"duration":10000,
		"debuff":True,
	},
	"charging":{
		"name":"Charging",
		"skin":"condition_positive",
		"speed":30,
		"duration":3200,
	},
	"dash":{
		"name":"Dashing",
		"skin":"condition_positive",
		"set_speed":500,
		"persistent":True,
	},
	"blink":{
		"name":"Blinking",
		"skin":"condition_positive",
		"explanation":"Blink in progress",
	},
	"block":{
		"name":"PVP Block",
		"skin":"condition_neutral",
		"explanation":"After engaging in PVP, blocked from safely leaving!",
		"debuff":True,
		"persistent":True,
	},
	"town":{
		"name":"Town",
		"skin":"condition_positive",
		"explanation":"Town in progress",
		"channel":True,
		"can_move":True,
		"duration":3000,
	},
	"fishing":{
		"name":"Fishing",
		"skin":"skill_fishing",
		"explanation":"Fishing in progress",
		"channel":True,
		"duration_min":5000,
		"duration":15000,
	},
	"mining":{
		"name":"Mining",
		"skin":"skill_mining",
		"explanation":"Mining in progress",
		"channel":True,
		"duration_min":5000,
		"duration":15000,
	},
	"pickpocket":{
		"name":"Pickpocket",
		"skin":"skill_pickpocket",
		"explanation":"Pickpocket in progress",
		"channel":True,
		"duration_min":200,
		"duration":2200,
	},
	"sleeping":{
		"debuff":True,
		"name":"Sleeping",
		"duration_min":3000,
		"duration":8000,
	},
}

if 0:
	for name in games["tarot"]["cards"]:
		conditions["tarot_%s"%name]={"skin":"tarot","name":"Tarot Card","type":"tarot","ui":True}
		for (num,val) in [["2",2],["3",3],["4",4],["5",5],["6",6],["7",7],["8",8],["9",9],["10",10],["ace",20],["king",15],["knight",17],["page",12],["queen",14]]:
			color=""
			if num in name and "swords" in name:
				conditions["tarot_%s"%name]["str"]=val; color="swords"
			if num in name and "wands" in name:
				conditions["tarot_%s"%name]["int"]=val; color="wands"
			if num in name and "cups" in name:
				conditions["tarot_%s"%name]["dex"]=val; color="cups"
			if num in name and "pentacles" in name:
				conditions["tarot_%s"%name]["vit"]=-val; color="pentacles"
			if color:
				conditions["tarot_%s"%name]["minor"]="%s_%s"%(num,color)
				conditions["tarot_%s"%name]["card"]="%s of %s"%(color.title(),num.title())
		if name=="fool":
			conditions["tarot_%s"%name]["miss"]=50
		if name=="chariot":
			conditions["tarot_%s"%name]["speed"]=16
		if name=="death":
			conditions["tarot_%s"%name]["vit"]=-30
			conditions["tarot_%s"%name]["frequency"]=-30
			conditions["tarot_%s"%name]["speed"]=-20
		if name=="devil":
			conditions["tarot_%s"%name]["xp"]=-99
			conditions["tarot_%s"%name]["luck"]=-99
			conditions["tarot_%s"%name]["vit"]=10
			conditions["tarot_%s"%name]["str"]=10
		if not conditions["tarot_%s"%name].get("minor"):
			conditions["tarot_%s"%name]["card"]=name.title()
			conditions["tarot_%s"%name]["major"]=name



