projectiles={
	"momentum":{
		"animation":"slash",
		"speed":320,
		"hit_animation":"slash1",
	},
	"quickpunch":{
		"animation":"slash",
		"speed":420,
		"hit_animation":"slash2",
		"hit_text":["PUNCH!","#41338B"],
	},
	"quickstab":{
		"animation":"slash",
		"speed":420,
		"hit_animation":"slash2",
		"hit_text":["STAB!","#41338B"],
	},
	"smash":{
		"animation":"slash",
		"speed":420,
		"hit_animation":"slash2",
		"hit_text":["SMASH!","#CBB892"],
	},
	"wmomentum":{
		"animation":"wslash",
		"speed":520,
		"hit_animation":"slash3",
	},
	"arrow":{
		"animation":"carrow",
		"speed":500,
		"hit_animation":"arrow_hit",
	},
	"crossbowarrow":{
		"animation":"carrow",
		"speed":700,
		"hit_animation":"arrow_hit",
	},
	"garrow":{
		"animation":"garrow",
		"speed":640,
		"hit_animation":"arrow_hit",
	},
	"poisonarrow":{
		"animation":"arrow1",
		"speed":400,
		"hit_animation":"arrow_hit",
		"hit_text":["POISONED!","poison"],
	},
	"pouch":{
		"animation":"poucharrow",
		"speed":300,
		"hit_animation":"explode_b",
	},
	"firearrow":{
		"animation":"firearrow",
		"speed":460,
		"hit_animation":"arrow_hit",
	},
	"frostarrow":{
		"animation":"frostarrow",
		"speed":580,
		"hit_animation":"icecrack",
	},
	"acid":{
		"animation":"acid",
		"speed":280,
	},
	"supershot":{
		"animation":"superarrow",
		"speed":600,
		"hit_animation":"supershot",
		"hit_text":["SUPERSHOT!","#9B172E"],
	},
	"magic":{
		"animation":"magic1",
		"speed":400,
		"hit_animation":"explode_c",
	},
	"bigmagic":{
		"animation":"magic0",
		"speed":320,
		"hit_animation":"explode_c",
	},
	"wandy":{
		"animation":"wandy",
		"speed":560,
		"hit_animation":"explode_c",
	},
	"pinky":{
		"animation":"pinky",
		"speed":460,
		"hit_animation":"explode_c",
	},
	"magic_purple":{
		"animation":"magic3",
		"speed":400,
		"hit_animation":"explode_c",
	},
	"magic_divine":{
		"animation":"magic4",
		"speed":480,
		"hit_animation":"explode_c",
	},
	"mmagic":{
		"animation":"mblob_purplish",
		"speed":400,
		"hit_animation":"explode_p",
	},
	"pmagic":{
		"animation":"magic2",
		"speed":360,
		"hit_animation":"explode_p",
	},
	"stone":{
		"animation":"pblob",
		"speed":320,
		"hit_animation":"slash1",
	},
	"stone_k":{
		"animation":"pblob",
		"speed":320,
		"hit_animation":"explode_b",
	},
	"fireball":{
		"animation":"fireball",
		"speed":320,
		"hit_animation":"explode_c",
	},
	"frostball":{
		"animation":"frostball",
		"speed":420,
		"hit_animation":"explode_c",
	},
	"snowball":{
		"speed":180,
		"animation":"snowball",
		"hit_animation":"snowball_hit",
		"pure":True,
	},
	"plight":{
		"animation":"heal_projectile",
		"speed":120,
		"hit_animation":"heal",
	},
	"curse":{
		"animation":"curse_projectile",
		"speed":240,
		"hit_animation":"curse_new",
	},
	"cupid":{
		"animation":"cuarrow",
		"speed":320,
		"hit_animation":"heal",
	},
	"mentalburst":{
		"instant":True,
		"ray":"tiling_burstj",
		"kill_text":["POW!","#4C9AE0"],
		"hit_animation":"burst",
	},
	"purify":{
		"instant":True,
		"hit_text":["PURIFIED!","#DDCC7B"],
		"hit_animation":"flare_yellow",
	},
	"burst":{
		"instant":True,
		"ray":"tiling_burstj",
		"hit_animation":"burst",
	},
	"sburst":{ #small burst
		"instant":True,
		"ray":"tiling_burst",
		"hit_animation":"burst",
	},
	"gburst":{
		"instant":True,
		"ray":"tiling_burst_g",
		"hit_animation":"gburst",
	},
	"partyheal":{
		"instant":True,
		"hit_animation":"party_heal",
	}
}