docs={
	"functions":[
		#runner_functions
		"start_character",
		"stop_character",
		"command_character",
		"get_active_characters",
		"change_server",
		"in_pvp",
		"is_npc",
		"is_monster",
		"is_character",
		"interact",
		"use_nearest_door",
		"enter",
		"join",
		"activate",
		"shift",
		"throw_item",
		#"can_use",
		#"use",
		"use_skill",
		"reduce_cooldown",
		"bank_deposit",
		"bank_withdraw",
		"bank_store",
		"bank_retrieve",
		"bank_swap",
		"swap",
		"locate_item",
		"quantity",
		"item_properties",
		"item_grade",
		"item_value",
		"transport",
		"leave",
		"is_paused",
		"pause",
		"get_socket",
		"get_map",
		"set_message",
		"game_log",
		"log",
		"safe_log",
		"get_focus",
		"get_target_of",
		"get_target",
		"get_targeted_monster",
		"change_target",
		"can_move_to",
		"xmove",
		"is_in_range",
		"is_on_cooldown",
		"can_attack",
		"can_heal",
		"is_moving",
		"is_transporting",
		"attack",
		"heal",
		"buy",
		"buy_with_gold",
		"buy_with_shells",
		"sell",
		"consume",
		"equip",
		"unequip",
		"lock_item",
		"seal_item",
		"unlock_item",
		"open_stand",
		"close_stand",
		"trade",
		"trade_buy",
		"trade_sell",
		"wishlist",
		"giveaway",
		"join_giveaway",
		"upgrade",
		"compound",
		"craft",
		"auto_craft",
		"exchange",
		"exchange_buy",
		"say",
		"party_say",
		"pm",
		"move",
		"cruise",
		"equip_cx",
		"show_json",
		"get_characters",
		"get_servers",
		"get_party",
		"get_player",
		"get_monster",
		"get_entity",
		"find_npc",
		"get_nearest_monster",
		"get_nearest_hostile",
		"get_nearest_npc",
		"use_hp_or_mp",
		"loot",
		"get_chests",
		"send_gold",
		"send_item",
		"send_cx",
		"send_mail",
		"destroy",
		"send_party_invite",
		"send_party_request",
		"accept_party_invite",
		"accept_party_request",
		"leave_party",
		"kick_party_member",
		"accept_magiport",
		"unfriend",
		"respawn",
		"set_home",
		"handle_death",
		"handle_command",
		"send_cm",
		"on_disappear",
		"on_combined_damage",
		"on_party_invite",
		"on_party_request",
		"on_destroy",
		"on_draw",
		"on_game_event",
		"draw_line",
		"draw_circle",
		"clear_drawings",
		#"auto_reload",
		"get",
		"set",
		#"game",
		"preview_item",
		"set_skillbar",
		"set_keymap",
		"map_key",
		"unmap_key",
		"reset_mappings",
		"load_code",
		"require_code",
		"upload_code",
		"get_active_code_slot",
		"get_edited_code_slot",
		"disconnect",
		"smart_move",
		"stop",
		"performance_trick",
		#common_functions
		"distance",
		"can_walk",
		"can_transport",
		"is_disabled",
		"is_number",
		"is_string",
		"is_function",
		"is_object",
		"is_array",
	],
	"documented":[
		"attack",
		"heal",
		"buy",
		"upgrade",
		"compound",
		"use_skill"
	],
	"javascript":[
		["Javascript Intro","js,learn,tutorial,number,integer,date,var,variable,let,const","https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Introduction"],
		["String","string","https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String"],
		["Array","array","https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array"],
		["Object","object,player,character,monster","https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object"],
		["Math","math,sqrt,min,max,sin,cos","https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math"],
		["Date","date,time","https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date"],
		["Promise","promise,then","https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise"],
		["Timeouts and Intervals","setTimeout,setInterval","https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Timeouts_and_intervals"],
	],
	"tutorial":[
		{
			"key":"helloworld",
			"tasks":[],
			"title":"Welcome!",
		},
		{
			"key":"learntofight",
			"tasks":["killagoo","firstloot"],
			"title":"Learn to Fight!",
		},
		{
			"key":"interface",
			"tasks":["character","inventory","stats","skills","guide","com","code","travel","settings"],
			"title":"Game Interface",
		},
		# {
		# 	"key":"inventory",
		# 	"tasks":["inventory","sell"],
		# 	"title":"Open Your Inventory!"
		# },
		{
			"key":"upgrade",
			"tasks":["buyscrolls","upgrade","addstats"],
			"title":"Learn to Upgrade!",
		},
		{
			"key":"compound",
			"tasks":["buycscroll0","compound"],
			"title":"Learn to Combine!",
		},
		# {
		# 	"key":"equip",
		# 	"tasks":["equip","unequip"],
		# 	"title":"Learn to Equip",
		# },
		{
			"key":"bank",
			"tasks":["bank","store","deposit"],
			"title":"Discover the Bank",
		},
		{
			"key":"hellocode",
			"tasks":["engage","x"],
			"title":"Hello CODE!",
		},
		# {
		# 	"key":"0.2-com",
		# 	"tasks":["friends","nearby","server","realm","character"],
		# 	"title":"The Communicator",
		# },
		# {
		# 	"key":"1-move",
		# 	"tasks":["firstmoves","codemove"],
		# 	"title":"Learn to Move",
		# },
		# {
		# 	"key":"2-attack",
		# 	"tasks":["hitthegoos"],
		# 	"title":"Learn to Attack"
		# }
		{
			"key":"theend",
			"tasks":[],
			"title":"The End",
		},
	],
	"tasks":{
		"character":"Your Character",
		"inventory":"Inventory",
		"stats":"Character Stats",
		"skills":"Skills",
		"guide":"Game Guide",
		"com":"Communicator",
		"code":"CODE!",
		"travel":"Travel Anywhere",
		"settings":"Settings",
		"engage":"Just Engage",
		"x":"Snippet",
		"buyscrolls":"Buy Scrolls",
		"buycscroll0":"Buy the Scroll",
		"upgrade":"Upgrade",
		"addstats":"Use Stat Scrolls",
		"killagoo":"Kill a Goo",
		"firstloot":"Loot the Chest",
		"compound":"Compound!",
		"bank":"Enter the Bank",
		"store":"Store an Item",
		"deposit":"Deposit Gold",
	},
	"rewards":{
		"c0":[[1,"open","cosmo0"]],
	},
	"guide":[
		# ["faq","Frequently Asked Questions","#CA3C93",
		# 	[
		# 		["faq-soon","Coming Soon","#C01941"],
		# 	]
		# ],
		["basics","The Basics","","#97D058"],
		["stats","Attributes, Classes, Skills","","#33C9CC"],
		["items","Items, Upgrades, Crafting","items","#58ABFF",],
		["limits","Servers, Limits, Rules","","#E67419"],
		["pvp","PVP, Dueling","","#FD6058"],
		["looks","Cosmetics","","#FD9DF9"],
		["code","Learn CODE","","#E78E4E",
			[
				["javascript-and-stuff","Javascript and the Basics","","#4FE450",
				[
					["1-easy","Motivational Speech","","#C01941"],
					["2-javascript","Hello World!","","#7C81C3"],
					["3-security","Security First!","","#71C76F"],
				]
				],
				["4-basicmath","Some Math","","#3BA6C3",
					[
						["4.1-coordinates","Coordinate System","","#FD9757"],
						["4.2-walkinghalfway","Walking Halfway","","#FC2636"],
						["4.G-geometry","Geometry","","#FC3B94"],
					]
				],
				["6-items101","Items 101","items","#E28A27"],
				["8-code-slots-and-files","Code Slots and Files","files,slots,save,local","#7E8895"],
				["7-using-skills","Using Skills","skills","#E24148"],
				["persistent-values","Add Persistence!","get,set","#7A8EE4"],
				["X.sub-architecture","Game and Code Architecture","","#8785B2"],
				["5-goingplaces","Going Places","","#4BC78F"],
				["X-advancedtopics","Advanced Topics","","#8044C4",
					[	["X.sub-cli","CLI: An Introduction","cli","#79C6C1"],
						["X.sub-cm","Code Messages","cm,messages","#B3C77A"],
						["X.sub-api","API Call System","api","#69C6C1"],
					]
				],
			]
		],
		["multi","Multiple Ways to Run Multiple Characters","multi,deploy","#5997FF"],
		["advanced","Advanced Topics","","#CA3C93",
			[
				["tracktrix","Scoring for Tracktrix Achievements","","#5461C3"],
				#["faq-soon","Looting Dynamics (Soon)","","#C01941"],
			]
		],
	],
	"references":[
		["data-character","Character Objects","characters,players"],
		["data-monster","Monster Objects","monsters,entity"],
		#["data-npc","NPC Objects","npcs"],
		["events-character","Character Events","events"],
		["events-game","Game Events","game,events"],
	],
	"images":{
		'bank':{'url':'http://lh3.googleusercontent.com/c69Ijb6nu4wOfCD5m3yGKbp6-CYCdbkMdqpKuecH7F9oXBFYDcyDopmspOCo2uTL1AO7npbO5dAoPfIHXn_Y19Ev41AURBc','width':1520,'height':824},
		'character_button':{'url':'http://lh3.googleusercontent.com/HZI8xM8UQ-VTTiz9I1WAC7wQy9cPHbeNQ11PuQK0kbydWEF7Rmc9NJYcsHYb82PXJiTDzAF1BAk9Fk28PT1iglsUOUlnGpbN','width':382,'height':266},
		'topleft_character':{'url':'http://lh3.googleusercontent.com/oSB2aD44TMMup4cV_O-iXFj0iQ6zE70gPGSTLkYIrL1yWUkjog1GZLSTfmJ5WmwZyT3FkkoYNkWSqMOuqyIfsXT2R3MTYVJ_','width':998,'height':602},
		'topleft_monster':{'url':'http://lh3.googleusercontent.com/g2wTE8fuzg7KzUmqzPAjsrP9fS7b4I7vLK_p1Nqa7_jgTAOUVfZNz05qafUoFaiQqno85dw2vTsQfpMIL5gsrGOcw9KeFSLvkQ','width':486,'height':428},
		'newyear_tree':{'url':'http://lh3.googleusercontent.com/BbENUEvYLaLvbHPdk9uWDkMwhh59v4Sd_V_wex6whMDiLr9h2ZDCmDN-i5XxTehHbnaRQPrnd-msEgSsjaQrLWxCNQz6uvvA','width':528,'height':516},
		'cue':{'url':'http://lh3.googleusercontent.com/h7ttABnKxQz0ca0p6jnq1DG5iNLw4Pac5Z1Bo800cRpxP2b9k-SQqY7yuYRVPLRIvCAvVBe3s2_EBUBR1TF3XptKR5jewcY8r9B1Xvr_dkKZ3ZE','width':396,'height':396},
		'upgrade':{'url':'http://lh3.googleusercontent.com/qhSgjFF4Qp94CeS-Dc62PgZU9LANN68x6GCrBdPVvVrQYOlHSGEpNb8sP926OLbtKesfQA8Elc9Ycgm5l1SO-4yvV7dxpNMc7cvJCPKvTGdZCw','width':426,'height':396},
	}
}

docs["functions"].sort()